/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Image;
import java.awt.event.MouseListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author nishu
 */
public class insert extends javax.swing.JFrame {

    /**
     * Creates new form insert
     */
    public insert() {
        initComponents();
        try {
            // TODO add your handling code here:
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","aaaaa");          
            java.sql.Statement st=con.createStatement();
            String s="select * from genre";
            ResultSet rs=st.executeQuery(s);
            while(rs.next())
            {
                genrebox.addItem(rs.getString(2));
            }
            }
            catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(search.class.getName()).log(Level.SEVERE, null, ex);
        }     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JTextField();
        year = new javax.swing.JTextField();
        runtime = new javax.swing.JTextField();
        director = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ratings = new javax.swing.JTextField();
        cast = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        poster = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        genrebox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(960, 580));
        getContentPane().setLayout(null);
        getContentPane().add(title);
        title.setBounds(180, 150, 210, 30);
        getContentPane().add(year);
        year.setBounds(180, 190, 210, 30);
        getContentPane().add(runtime);
        runtime.setBounds(180, 230, 210, 30);
        getContentPane().add(director);
        director.setBounds(180, 270, 210, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Movie Title:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 150, 110, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Release Year:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 200, 120, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Runtime:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 230, 120, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Director: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 270, 120, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Cast: ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 310, 50, 30);
        getContentPane().add(ratings);
        ratings.setBounds(180, 390, 210, 30);
        getContentPane().add(cast);
        cast.setBounds(180, 310, 210, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Ratings:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(90, 390, 70, 30);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Movie Database");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 960, 100);

        jButton1.setText("INSERT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(510, 490, 100, 30);

        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(630, 490, 100, 30);

        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(750, 490, 100, 30);

        poster.setBackground(new java.awt.Color(0, 0, 0));
        poster.setOpaque(true);
        getContentPane().add(poster);
        poster.setBounds(580, 130, 200, 250);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Poster :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(510, 140, 70, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("Genre: ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(80, 350, 80, 30);

        jButton4.setText("UPLOAD");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(630, 400, 100, 30);

        genrebox.setMaximumRowCount(25);
        genrebox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                genreboxMouseClicked(evt);
            }
        });
        genrebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genreboxActionPerformed(evt);
            }
        });
        getContentPane().add(genrebox);
        genrebox.setBounds(180, 350, 210, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/projector_nota.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 960, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        option o= new option();
        o.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        title.setText("");
        director.setText("");
        runtime.setText("");
        year.setText("");
        cast.setText("");
        ratings.setText("");
        poster.setIcon(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    String selectedImagePath = null;
    String filename = null;
    InputStream inputstream = null;
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:  
        JFileChooser filechooser = new JFileChooser();
        //choose only "png", "jpg", "jpeg"
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
        filechooser.addChoosableFileFilter(fnef);
        int openDialog = filechooser.showOpenDialog(null);
        if (openDialog == JFileChooser.APPROVE_OPTION) {
            File selectedFile = filechooser.getSelectedFile();
            selectedImagePath = selectedFile.getAbsolutePath();
            filename = selectedFile.getName();
            //textFieldDisplayPath.setText(selectedImagePath);
            ImageIcon ii = new ImageIcon(selectedImagePath);
            //resizing image to fit jlabel
            Image image = ii.getImage().getScaledInstance(poster.getWidth(), poster.getHeight(), Image.SCALE_SMOOTH); 
            poster.setIcon(new ImageIcon(image));
        }     
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:        
        try
{
	Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","aaaaa");
	String s1= title.getText();
	String s2= year.getText();
	String s3= runtime.getText();
	String s4= director.getText();
	String s5= cast.getText();
	String se= genrebox.getSelectedItem().toString();
	String s7= ratings.getText();
	int r1=Integer.parseInt(s3);
	float r2=Float.parseFloat(s7);       
        
        String sql="insert into movies (TITLE, IMAGES,`RELEASE YEAR`, RUNTIME, DIRECTOR, CAST, GENRE, RATE) values (?, ?, ?, ?, ?, ?, ?, ?)";
	PreparedStatement st;
        try{
            inputstream = new FileInputStream(new File(selectedImagePath));
            st = con.prepareStatement(sql);
            st.setString(1, s1);
            st.setBlob(2, inputstream);
            st.setString(3, s2);
            st.setInt(4, r1); 
            st.setString(5, s4);
            st.setString(6, s5);
            st.setString(7, se);
            st.setFloat(8,r2);
            st.execute();
            JOptionPane.showMessageDialog(null, "Successfully Inserted!");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error while inserting!, Recheck Please");
            System.out.println(e);
        }
}       catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error while inserting!, Recheck Please");
            System.out.println(e);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void genreboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genreboxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_genreboxActionPerformed

    private void genreboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genreboxMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_genreboxMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new insert().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cast;
    private javax.swing.JTextField director;
    private javax.swing.JComboBox<String> genrebox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel poster;
    private javax.swing.JTextField ratings;
    private javax.swing.JTextField runtime;
    private javax.swing.JTextField title;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
    
}
