/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author amish
 */
public class stats extends javax.swing.JFrame {

    /**
     * Creates new form stats
     */
    public stats() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        update = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        moviecount = new javax.swing.JTextField();
        seriecount = new javax.swing.JTextField();
        ratemovie = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        head = new javax.swing.JLabel();
        rateseries = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(960, 540));
        getContentPane().setLayout(null);

        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(570, 470, 100, 30);

        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(680, 470, 100, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("No. of movie records:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 170, 180, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("No. of series records:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 230, 180, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Max rating among Movies:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 290, 240, 20);

        moviecount.setEditable(false);
        getContentPane().add(moviecount);
        moviecount.setBounds(440, 170, 220, 30);

        seriecount.setEditable(false);
        getContentPane().add(seriecount);
        seriecount.setBounds(440, 230, 220, 30);

        ratemovie.setEditable(false);
        getContentPane().add(ratemovie);
        ratemovie.setBounds(440, 290, 220, 30);

        jPanel1.setOpaque(false);

        head.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        head.setForeground(new java.awt.Color(255, 255, 255));
        head.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        head.setText("DATABASE STATS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(head, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(head, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 960, 100);

        rateseries.setEditable(false);
        rateseries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateseriesActionPerformed(evt);
            }
        });
        getContentPane().add(rateseries);
        rateseries.setBounds(440, 350, 220, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Max rating among TV Series:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(169, 340, 240, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/BG1.png"))); // NOI18N
        jLabel4.setText("bg");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 960, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rateseriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateseriesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rateseriesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dashboard d= new dashboard();
        d.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            head.setVisible(true);
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","aaaaa");          
            java.sql.Statement stmt=con.createStatement();
            ResultSet s1= stmt.executeQuery("SELECT COUNT(TITLE) FROM MOVIES");                   
            while(s1.next())
            {
               moviecount.setText(""+s1.getString(1));
            }
            
            ResultSet s2= stmt.executeQuery("SELECT COUNT(TITLE) FROM TV_SERIES");
            while(s2.next())
            {
               seriecount.setText(""+s2.getString(1));
            }
            
            ResultSet s3= stmt.executeQuery("SELECT TITLE FROM MOVIES WHERE RATE IN (SELECT MAX(RATE) FROM MOVIES)");
            while(s3.next())
            {
               ratemovie.setText(""+s3.getString(1));
            }
            
            ResultSet s4= stmt.executeQuery("SELECT TITLE FROM TV_SERIES WHERE RATE IN (SELECT MAX(RATE) FROM TV_SERIES)");
            while(s4.next())
            {
               rateseries.setText(""+s4.getString(1));
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(search.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(search.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel head;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField moviecount;
    private javax.swing.JTextField ratemovie;
    private javax.swing.JTextField rateseries;
    private javax.swing.JTextField seriecount;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
